export const SWITCH_LANG = 'SWITCH_LANG';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';

export const WEBSOCKET_CONNECT = 'WEBSOCKET:CONNECT';
export const WEBSOCKET_OPEN = 'WEBSOCKET:OPEN';
export const WEBSOCKET_CLOSE = 'WEBSOCKET:CLOSE';
export const WEBSOCKET_MESSAGE = 'WEBSOCKET:MESSAGE';
export const WEBSOCKET_SEND = 'WEBSOCKET:SEND';
export const WEBSOCKET_DISCONNECT = 'WEBSOCKET:DISCONNECT';

export const EVENTSOURCE_CONNECT = 'EVENTSOURCE:CONNECT';
export const EVENTSOURCE_OPEN = 'EVENTSOURCE:OPEN';
export const EVENTSOURCE_CLOSE = 'EVENTSOURCE:CLOSE';
export const EVENTSOURCE_MESSAGE = 'EVENTSOURCE:MESSAGE';
export const EVENTSOURCE_DISCONNECT = 'EVENTSOURCE:DISCONNECT';